In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [7]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

print(iris_X[:2, :])
print(iris_y[:2])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
[0 0]


In [9]:
# systematic split and shuffle
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=0.3)
y_test

array([2, 1, 2, 0, 2, 0, 2, 1, 2, 0, 1, 2, 2, 0, 1, 0, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 1, 2, 2, 2, 0, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2, 1, 2, 1,
       2])

In [22]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

print(sum(knn.predict(X_test) == y_test) / len(y_test))
print(accuracy_score(knn.predict(X_test), y_test))

0.9777777777777777
0.9777777777777777
