In [1]:
import numpy as np

In [34]:
a = np.array([[1, 2, 3],
              [2, 3, 4]], 
              dtype=np.int16)
print(a.dtype)
print(a)

int16
[[1 2 3]
 [2 3 4]]


int
float
np.int32
np.float32

In [37]:
b = np.zeros((3,4), dtype=int)
c = np.ones((3,4))
print(b)
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
d = np.empty((2, 4))
d

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.74694933e-321, 1.42418444e-306,
        2.56761491e-312]])

In [50]:
e = np.arange(10,30,2).reshape((2,5))
e

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [47]:
f = np.linspace(1,10,20).reshape((4,5))
f

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])