In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])
b = np.arange(4)
a,b

(array([10, 20, 30, 40]), array([0, 1, 2, 3]))

In [9]:
print(a+b)
print(a*b)
print(b**2)
print(10 * np.sin(a))

[10 21 32 43]
[  0  20  60 120]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [13]:
print(b < 3)
print(b == 3)

[ True  True  True False]
[False False False  True]


In [19]:
a = np.array([0,1,1,1]).reshape((2,2))
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[0 1]
 [1 1]]
[[0 1]
 [2 3]]


In [21]:
print(a*b)
print(np.dot(a,b))
print(a.dot(b))

[[0 1]
 [2 3]]
[[2 3]
 [2 4]]
[[2 3]
 [2 4]]


In [17]:
a = np.array([[1,2,4,3],
               [3,4,6,5]])
print(a)
print(np.sum(a))
print(np.min(a, axis=0))   # cross row , return a row
print(np.max(a, axis=1))   # cross column , return a column

[[1 2 4 3]
 [3 4 6 5]]
28
[1 2 4 3]
[4 6]


In [57]:
aa = np.array([[1,2,4,3],
               [2,0,6,5]])
print(aa)
print(np.argmin(aa))
print(np.argmax(aa, axis=1))

[[1 2 4 3]
 [2 0 6 5]]
5
[2 2]


In [7]:
aa = np.array([[1,2,4,3],
               [2,0,6,5]])
print(np.mean(aa))
print(np.mean)
print(aa.mean())
print(aa.mean)
print(np.average(aa))

2.875
<function mean at 0x000001BE231EF910>
2.875
<built-in method mean of numpy.ndarray object at 0x000001BE234507B0>
2.875


In [59]:
aa = np.array([[1,2,4,3],
               [2,0,6,5]])
print(aa)
print(np.median(aa))
print(np.cumsum(aa))
print(np.diff(aa))

[[1 2 4 3]
 [2 0 6 5]]
2.5
[ 1  3  7 10 12 12 18 23]
[[ 1  2 -1]
 [-2  6 -1]]


In [61]:
aa = np.array([[1,2,4,3],
               [2,0,6,5]])
print(aa)
print(np.nonzero(aa))  # all non-zero (row and column) indices

[[1 2 4 3]
 [2 0 6 5]]
(array([0, 0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 0, 2, 3], dtype=int64))


In [14]:
aa = np.arange(14,2,-1).reshape((3,4))
print(aa)
print(np.sort(aa))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [15]:
aa = np.arange(14,2,-1).reshape((3,4))
print(np.transpose(aa))
print(aa.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [16]:
aa = np.arange(14,2,-1).reshape((3,4))
print(np.clip(aa,5,9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
