In [2]:
import numpy as np

In [5]:
A = np.arange(3,15).reshape(3,4)
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [16]:
print(A[2])
print(A[1,1])
print(A[1][1])
print(A[1,:])
print(np.where(A == 8))

[11 12 13 14]
8
8
[ 7  8  9 10]
(array([1], dtype=int64), array([1], dtype=int64))


In [18]:
for row in A:
    print(row)

for column in A.T:
    print(column)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [23]:
print(A.flatten())
print(A.flat)
for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
