In [2]:
import numpy as np

In [4]:
a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.vstack((a,b))   # vertical
d = np.hstack((a,b))   # horizontal
print('c:', c)
print('d:', d)
print(a.shape, c.shape, d.shape)
print(a.shape, a.T.shape)   # not work~

c: [[1 1 1]
 [2 2 2]]
d: [1 1 1 2 2 2]
(3,) (2, 3) (6,)
(3,) (3,)


In [27]:
aa = np.array([1,1,1])[:,np.newaxis]
bb = np.array([2,2,2])[:,np.newaxis]
print(aa)
print(aa.shape)

[[1]
 [1]
 [1]]
(3, 1)


In [31]:
cc = np.vstack((aa,bb))   # vertical
dd = np.hstack((aa,bb,aa))   # horizontal
print('cc:', cc)
print('dd:', dd)
print(aa.shape, cc.shape, dd.shape)

cc: [[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
dd: [[1 2 1]
 [1 2 1]
 [1 2 1]]
(3, 1) (6, 1) (3, 3)


In [34]:
cc1 = np.concatenate((aa,bb,aa,bb), axis=1)   # 0 vertical 1 horizontal
cc1

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])