In [1]:
import numpy as np

In [26]:
a = np.arange(4)
b = a
c = a
d = b
print(a)
print(b is a)
print(c is a)
print(d is a)

[0 1 2 3]
True
True
True


In [27]:
a[0] = 11
print('a:',a)
d[1:3] = [22,33]
print('a:',a)

a: [11  1  2  3]
a: [11 22 33  3]


In [52]:
a = np.arange(4)
b = a
b_deep = a.copy()
print(b)
print(b_deep)

[0 1 2 3]
[0 1 2 3]


In [53]:
a[3] = 44
print('b:', b)
print('b_deep:', b_deep)

b: [ 0  1  2 44]
b_deep: [0 1 2 3]
